version: '3.8'
services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - app-network

  server:
    build: ./server
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=monapp
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: monapp
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge
